version: "3.8"
services:
  sopsage:
    container_name: sopsage
    build: "."
      
    image: sopsage
    stdin_open: true
    tty: true

    volumes:
     - ../_configs/${CONFIG_ID:-defaults}:/sopsage/configs    
#     - ../_public-keys/${CONFIG_ID:-dev-server-1}:/sopsage/keys
#     - ../_configs/${CONFIG_ID:-dev-server-1}:/sopsage/configs
#    - ${KEYS_DIRECTORY:-../_public-keys/dev-server-1}:/sopsage-keys
#    - ${DATA_DIRECTORY:-./}:/sopsage-data
#    networks:
#      - db-network

#networks:
# db-network:
#  name: mysql-setup_test-db-net
#  external: true
